services:
  - type: web
    name: neuroweb-dkg-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRIVATE_KEY
        sync: false
